### ISSUE TITLE
pytest does not work

### ISSUE THREAD

**Issue by igchin** [openCEMorg/openCEM#18]
Hi

I have just installed and run openCEM for the first time.  These are the steps I have folllowed:

1. clone a copy of the files to my local drive.
2. As I am using Windows rather than Mac, I use the glpk solver instead of the cbc.  Therefore, in the environment.yml, I changed the dependency coincbc to glpk.
3. I installed the environment using command "conda env create -f environment.yml"
4. I activated the environment using command "conda activate opencem"
5. In the environment, I installed the dependencies using the command "pip install -r requirements.txt".
6. Then, I tested the installation using the command "pytest --solver=glpk"

But I got the error message below.  Any idea why that is the case?  

Thanks so much for your help.

[error.txt](https://github.com/openCEMorg/openCEM/files/5112257/error.txt)

**Comment by jotaigna** [comment]
Windows specific instructions to install and test openCEM have been provided in the Wiki. Your error seems to suggest that the test suite did not correctly call a solver and was thus not able to run the test. Either install cbc as the instructions on the wiki for windows or ensure that your solver works correctly from the command prompt.
